### ISSUE TITLE
Map view

### ISSUE THREAD

**Issue by maraf** [neptuo/Recollections#19]
Another view beside timeline.

- [x] #6 - GPS for entries.
- [x] #73 - Map in entry detail.
- [x] #74 - List GPS entries.
- [x] #79 - Entries view on map.
