### ISSUE TITLE
Premium features

### ISSUE THREAD

**Issue by maraf** [neptuo/Recollections#70]
**Features:**
- [x] #211 - Store original images.
- [x] #210 - Unlimited images in entry.
- [x] #224 - Unlimited GPS in entry.

**Notes:**
- Mapy.cz requires premium account for use in payed apps.

**Comment by maraf** [comment]
We should do it, but without any payment. Just the administrator to mark accounts as premium.
